<Type Name="DuplicateKeyException" FullName="System.Data.Linq.DuplicateKeyException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="6bd219cfebbb986e85bdd19cb451d6607ddd02fe" /><Meta Name="ms.sourcegitcommit" Value="f1d16425528e237257ca3b58eb49217a514849ea" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="es-ES" /><Meta Name="ms.lasthandoff" Value="04/24/2019" /><Meta Name="ms.locfileid" Value="63893934" /></Metadata><TypeSignature Language="C#" Value="public class DuplicateKeyException : InvalidOperationException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit DuplicateKeyException extends System.InvalidOperationException" />
  <TypeSignature Language="DocId" Value="T:System.Data.Linq.DuplicateKeyException" />
  <TypeSignature Language="VB.NET" Value="Public Class DuplicateKeyException&#xA;Inherits InvalidOperationException" />
  <TypeSignature Language="C++ CLI" Value="public ref class DuplicateKeyException : InvalidOperationException" />
  <TypeSignature Language="F#" Value="type DuplicateKeyException = class&#xA;    inherit InvalidOperationException" />
  <AssemblyInfo>
    <AssemblyName>System.Data.Linq</AssemblyName>
    <AssemblyVersion>3.5.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.InvalidOperationException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="ba319-101">Se produce cuando se intenta agregar un objeto a la memoria caché de identidad utilizando una clave que ya se utiliza.</span><span class="sxs-lookup"><span data-stu-id="ba319-101">Thrown when an attempt is made to add an object to the identity cache by using a key that is already being used.</span></span></summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Data.Linq</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="ba319-102">Inicializa una nueva instancia de la clase <see cref="T:System.Data.Linq.DuplicateKeyException" />.</span><span class="sxs-lookup"><span data-stu-id="ba319-102">Initializes a new instance of the <see cref="T:System.Data.Linq.DuplicateKeyException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public DuplicateKeyException (object duplicate);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(object duplicate) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Data.Linq.DuplicateKeyException.#ctor(System.Object)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (duplicate As Object)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; DuplicateKeyException(System::Object ^ duplicate);" />
      <MemberSignature Language="F#" Value="new System.Data.Linq.DuplicateKeyException : obj -&gt; System.Data.Linq.DuplicateKeyException" Usage="new System.Data.Linq.DuplicateKeyException duplicate" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Data.Linq</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="duplicate" Type="System.Object" />
      </Parameters>
      <Docs>
        <param name="duplicate"><span data-ttu-id="ba319-103">Clave duplicada que origina que se produzca la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-103">The duplicate key that caused the exception to be thrown.</span></span></param>
        <summary><span data-ttu-id="ba319-104">Inicializa una nueva instancia de la clase <see cref="T:System.Data.Linq.DuplicateKeyException" />.</span><span class="sxs-lookup"><span data-stu-id="ba319-104">Initializes a new instance of the <see cref="T:System.Data.Linq.DuplicateKeyException" /> class.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public DuplicateKeyException (object duplicate, string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(object duplicate, string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (duplicate As Object, message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; DuplicateKeyException(System::Object ^ duplicate, System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Data.Linq.DuplicateKeyException : obj * string -&gt; System.Data.Linq.DuplicateKeyException" Usage="new System.Data.Linq.DuplicateKeyException (duplicate, message)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Data.Linq</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="duplicate" Type="System.Object" />
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="duplicate"><span data-ttu-id="ba319-105">Clave duplicada que origina que se produzca la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-105">The duplicate key that caused the exception to be thrown.</span></span></param>
        <param name="message"><span data-ttu-id="ba319-106">Mensaje mostrado cuando se produce la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-106">The message to appear when the exception is thrown.</span></span></param>
        <summary><span data-ttu-id="ba319-107">Inicializa una nueva instancia de la clase <see cref="T:System.Data.Linq.DuplicateKeyException" /> haciendo referencia a la clave duplicada y proporcionando un mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="ba319-107">Initializes a new instance of the <see cref="T:System.Data.Linq.DuplicateKeyException" /> class by referencing the duplicate key and providing an error message.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public DuplicateKeyException (object duplicate, string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(object duplicate, string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (duplicate As Object, message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; DuplicateKeyException(System::Object ^ duplicate, System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.Data.Linq.DuplicateKeyException : obj * string * Exception -&gt; System.Data.Linq.DuplicateKeyException" Usage="new System.Data.Linq.DuplicateKeyException (duplicate, message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Data.Linq</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="duplicate" Type="System.Object" />
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="duplicate"><span data-ttu-id="ba319-108">Clave duplicada que origina que se produzca la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-108">The duplicate key that caused the exception to be thrown.</span></span></param>
        <param name="message"><span data-ttu-id="ba319-109">Mensaje mostrado cuando se produce la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-109">The message to appear when the exception is thrown.</span></span></param>
        <param name="innerException"><span data-ttu-id="ba319-110">Excepción previa que hizo que se produzca la excepción <see cref="T:System.Data.Linq.DuplicateKeyException" />.</span><span class="sxs-lookup"><span data-stu-id="ba319-110">The previous exception that caused the <see cref="T:System.Data.Linq.DuplicateKeyException" /> exception to be thrown.</span></span></param>
        <summary><span data-ttu-id="ba319-111">Inicializa una nueva instancia de la clase <see cref="T:System.Data.Linq.DuplicateKeyException" /> haciendo referencia a la clave duplicada, proporcionando un mensaje de error y especificando la excepción que produjo esta excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-111">Initializes a new instance of the <see cref="T:System.Data.Linq.DuplicateKeyException" /> class by referencing the duplicate key, providing an error message, and specifying the exception that caused this exception to be thrown.</span></span></summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="Object">
      <MemberSignature Language="C#" Value="public object Object { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance object Object" />
      <MemberSignature Language="DocId" Value="P:System.Data.Linq.DuplicateKeyException.Object" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Object As Object" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Object ^ Object { System::Object ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Object : obj" Usage="System.Data.Linq.DuplicateKeyException.Object" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Data.Linq</AssemblyName>
        <AssemblyVersion>3.5.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>get: System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Object</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="ba319-112">Obtiene el objeto que produjo la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-112">Gets the object that caused the exception.</span></span></summary>
        <value><span data-ttu-id="ba319-113">Objeto que produjo la excepción.</span><span class="sxs-lookup"><span data-stu-id="ba319-113">The object that caused the exception.</span></span></value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>