<Type Name="XamlInternalException" FullName="System.Xaml.XamlInternalException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="31a5b50c108a5d83d5d861f73baa68fc671e9077" />
    <Meta Name="ms.sourcegitcommit" Value="c0c07dbd19cd7017243f9ac36915755f79bc8da6" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="es-ES" />
    <Meta Name="ms.lasthandoff" Value="11/27/2018" />
    <Meta Name="ms.locfileid" Value="52383826" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class XamlInternalException : System.Xaml.XamlException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit XamlInternalException extends System.Xaml.XamlException" />
  <TypeSignature Language="DocId" Value="T:System.Xaml.XamlInternalException" />
  <TypeSignature Language="VB.NET" Value="Public Class XamlInternalException&#xA;Inherits XamlException" />
  <TypeSignature Language="C++ CLI" Value="public ref class XamlInternalException : System::Xaml::XamlException" />
  <TypeSignature Language="F#" Value="type XamlInternalException = class&#xA;    inherit XamlException" />
  <AssemblyInfo>
    <AssemblyName>System.Xaml</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Xaml.XamlException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="578cf-101">Excepción que se inicia si se producen incoherencias internas durante la lectura y la escritura de XAML.</span>
      <span class="sxs-lookup">
        <span data-stu-id="578cf-101">The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="578cf-102">Esta excepción normalmente se produce sólo cuando algún aspecto del lector XAML o sistema de escritura XAML se ha ampliado el código y las incoherencias o problemas de implementación se ha producido pasadas el código del sistema de servicios XAML de .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="578cf-102">This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</span></span> <span data-ttu-id="578cf-103">No deberían producir las excepciones que se ha originado de terceros, como análisis de XAML y encontrar errores en el XAML, <xref:System.Xaml.XamlInternalException>y en su lugar, debe iniciar otras excepciones como <xref:System.Xaml.XamlParseException> o <xref:System.Xaml.XamlObjectWriterException>.</span><span class="sxs-lookup"><span data-stu-id="578cf-103">Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <xref:System.Xaml.XamlInternalException>, and should instead throw other exceptions such as <xref:System.Xaml.XamlParseException> or <xref:System.Xaml.XamlObjectWriterException>.</span></span>  
  
 <span data-ttu-id="578cf-104">Si está escribiendo código que extiende los servicios XAML de .NET Framework, en concreto, si está escribiendo código para un lector XAML o la implementación de sistema de escritura XAML, debe mantener esta distinción entre <xref:System.Xaml.XamlInternalException> y las excepciones relacionadas con XAML.</span><span class="sxs-lookup"><span data-stu-id="578cf-104">If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <xref:System.Xaml.XamlInternalException> and the other XAML-related exceptions.</span></span> <span data-ttu-id="578cf-105">El código debe producir solo <xref:System.Xaml.XamlInternalException> en casos donde más extensiones de la clase infringen algunos patrones de implementación o el principio de diseño que define el código que se puede llamar.</span><span class="sxs-lookup"><span data-stu-id="578cf-105">Your code should only throw <xref:System.Xaml.XamlInternalException> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</span></span> <span data-ttu-id="578cf-106">El código debe iniciar otras excepciones específicas de XAML para la excepción de los casos donde el lector de XAML o la implementación de sistema de escritura XAML se usa sin la extensión y se usa para cargar XAML de terceros, el contexto de esquema XAML de terceros y así sucesivamente.</span><span class="sxs-lookup"><span data-stu-id="578cf-106">Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Xaml.XamlParseException" />
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="578cf-107">Inicializa una nueva instancia de la clase <see cref="T:System.Xaml.XamlInternalException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-107">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="578cf-108">Inicializa una nueva instancia de la clase <see cref="T:System.Xaml.XamlInternalException" /> con un mensaje proporcionado por el sistema que describe el error.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-108">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a system-supplied message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlInternalException : string -&gt; System.Xaml.XamlInternalException" Usage="new System.Xaml.XamlInternalException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="578cf-109">Mensaje que describe la excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-109">The message that describes the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="578cf-110">Inicializa una nueva instancia de la clase <see cref="T:System.Xaml.XamlInternalException" /> con un mensaje especificado que describe el error.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-110">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a specified message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected XamlInternalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; XamlInternalException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlInternalException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.Xaml.XamlInternalException" Usage="new System.Xaml.XamlInternalException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="578cf-111">Objeto que contiene los datos del objeto serializados.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-111">The object that holds the serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="578cf-112">Información contextual acerca del origen o del destino.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-112">The contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="578cf-113">Inicializa una nueva instancia de la clase <see cref="T:System.Xaml.XamlInternalException" /> con datos serializados.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-113">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlInternalException : string * Exception -&gt; System.Xaml.XamlInternalException" Usage="new System.Xaml.XamlInternalException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="578cf-114">Mensaje que describe la excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-114">The message that describes the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="578cf-115">Excepción que es la causa de la excepción actual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-115">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="578cf-116">Si el parámetro <paramref name="innerException" /> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-116">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="578cf-117">Inicializa una nueva instancia de la clase <see cref="T:System.Xaml.XamlInternalException" /> con el mensaje de error especificado y una referencia a la excepción interna que representa la causa de esta excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="578cf-117">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>